# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google_search.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13google_search.proto\"\xd1\x03\n\x03Ved\x12\x12\n\nlink_index\x18\x01 \x01(\x05\x12\x11\n\tlink_type\x18\x02 \x01(\x05\x12\n\n\x02v3\x18\x03 \x01(\x05\x12\n\n\x02v4\x18\x04 \x01(\x05\x12\x1b\n\x13sub_result_position\x18\x05 \x01(\x05\x12\x17\n\x0fresult_position\x18\x06 \x01(\x05\x12\x15\n\rresults_start\x18\x07 \x01(\x05\x12\n\n\x02v8\x18\x08 \x01(\x05\x12\n\n\x02v9\x18\t \x01(\x05\x12\x0b\n\x03v10\x18\n \x01(\x05\x12\x0b\n\x03v11\x18\x0b \x01(\x05\x12\x0b\n\x03v12\x18\x0c \x01(\x05\x12%\n\tv13_Outer\x18\r \x01(\x0b\x32\x12.Ved.v13_Outer_Msg\x12\x0b\n\x03v14\x18\x0e \x01(\x05\x12\x19\n\x03v15\x18\x0f \x01(\x0b\x32\x0c.Ved.v15_Msg\x1a\x86\x01\n\rv13_Outer_Msg\x12\x33\n\tv13_Inner\x18\x01 \x01(\x0b\x32 .Ved.v13_Outer_Msg.v13_Inner_Msg\x1a@\n\rv13_Inner_Msg\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\r\n\x05v13_2\x18\x02 \x01(\x07\x12\r\n\x05v13_3\x18\x03 \x01(\x07\x1a\'\n\x07v15_Msg\x12\r\n\x05v15_1\x18\x01 \x01(\x05\x12\r\n\x05v15_2\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google_search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VED']._serialized_start=24
  _globals['_VED']._serialized_end=489
  _globals['_VED_V13_OUTER_MSG']._serialized_start=314
  _globals['_VED_V13_OUTER_MSG']._serialized_end=448
  _globals['_VED_V13_OUTER_MSG_V13_INNER_MSG']._serialized_start=384
  _globals['_VED_V13_OUTER_MSG_V13_INNER_MSG']._serialized_end=448
  _globals['_VED_V15_MSG']._serialized_start=450
  _globals['_VED_V15_MSG']._serialized_end=489
# @@protoc_insertion_point(module_scope)
